import Link from 'next/link'
import './globals.css'
import LoginBtn from './loginbtn'
import LogoutBtn from './logoutbtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  // var conn = new WebSocket('ws://localhost:8080/socket');
  let session = await getServerSession(authOptions);
  console.log(session)
  //let test = navigator.mediaDevices.getUserMedia();
  // console.log(conn)

  return (
    <html lang="en">
      <body className='box-border'>
        <div className="bg-slate-500 flex justify-start p-3">
          <Link href={'/'}>Home</Link>
          <LoginBtn/>  
          {
            session != null 
            ? <LogoutBtn/> 
            : <Link href={'/register'} className='text-white text-lg font-bold'>sign up</Link>
          }
        </div>  
        {children}
      </body>
    </html>
  )
}
